#!/usr/bin/env python3
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
# asgard python in
import sys
sys.path.append('/home/shining/study/MS/asgard/python')
import CandidateData as cd
import CandidateSet as cs
import CandidatePlot as cp

PARAMS = ['SN', 'DM']
PlotTypes = ['corner', 'fullsky', 'DMtime']
phelp = """
    corner      Corner plot between DM, S/N
    fullsky     Full sky plot of candidates
    DMtime      Candidate DM vs Time with S/N as radius
"""

def parseArgs():
    import argparse
    # for parsing args
    # parent
    pap = argparse.ArgumentParser(prog='agcands', description='Command line to tool to visualize, vet candidates.', epilog='Part of Asgard', add_help=True)
    add = pap.add_argument
    add('cands', help='Candidates files', nargs='*')
    add('-o,ofile', help='Plot output file', dest='ofile')
    add('-p,plot', help='Plot type', choices=PlotTypes)
    add('--ant', help='Antenna', default='ea99', dest='ant')
    add('--snmax', help='S/N Max', default=100, dest='snmax', type=int)
    add('--snmin', help='S/N Min', default=5, dest='snmin', type=int)
    #
    return pap.parse_args()

if __name__ == '__main__':
    args = parseArgs()
    cp.snmax = args.snmax
    cp.snmin = args.snmin
    
    with PdfPages(args.ofile) as pdf:
        fig = plt.figure(dpi=300)
        for cfile in args.cands:
            cx = cs.CandidateData (cfile)
            cp.CVsTime(cx, afig=fig)
            pdf.savefig()
            plt.clf()
        plt.close()



