#!/usr/bin/python
### constants begin
CANDROOT = "/mnt/ssd/cand"
CANDROOT = "/home/shining/study/MS/vLITE/mkerr/cands"
ROOT = 0
### constants end
'''
    asgard::agcanalyze
    ------------------
    Python code to candidate aggregation for post data analysis. 
    Makes use of boost.mpi python library for it's MPI tasks.
    MO:
        - Group is decided.
        - A `CandidateData` object is created at each node which is brought 
            back to root node.
        - All the incoming CandidateData objects are aggregated into one 
            CandidateSet to be used for further processing
    NB
        - Default usecase is this program is run on vlite-nrl.
        Therefore, it has candidates. To override this, pass "-R" 
        TODO
'''
import os
import boost.mpi as bm
import CandidateData as cd
## variables for Bcast
group = None
enable_prom = False
def ParseArgs():
    import argparse
    '''For argument parsing'''
    ap = argparse.ArgumentParser(prog='agcanalyze', description='Asgard tool for quasi real time distributed candidate analysis.', epilog='Part of Asgard')
    add = ap.add_argument
    add('group', help = 'Group to work on.')
    # begin
    # aggreate to a file
    add('-o', help = 'Aggregate to a CandidateSet pickle in ROOT.', dest = 'ofile')
    # aggreate to a file with auto name
    add('-O', help = 'Same as -o but filename is group.', action='store_true')
    # plot 
    add('-p', help = 'Plot options.\nPlot will be made in ROOT.', dest = 'plot')
    # prometheus exporter
    add('-P', action='store_true', help = 'Enable prometheus exporter at all nodes.', dest='prometheus')
    # coincider
    add('-c', action='store_true', help = 'Run coincider on ROOT.', dest='coincide')
    # done
    return ap.parse_args()
def GetAntenna(x):
    '''
    Returns
    -------
    str: antenna
    '''
    fname, ext = os.path.splitext(x)
    # 20180521_162250_muos_ea02_kur.cand
    # 20180521_162250_muos_ea02.cand
    toks = fname.split('_')
    if len(toks) >= 4 and ext == '.cand':
        return toks[3]


if __name__ == '__main__':
    if bm.world.rank == ROOT:
        args = ParseArgs()
        enable_prom = args.prometheus
        group = args.group
        print args
    ## Housekeeping
    ## Bcasts
    group =  bm.broadcast(bm.world, group, ROOT)
    enable_prom = bm.broadcast(bm.world, enable_prom, ROOT)
    ## Actual work
    ### NB ROOT=vlite-nrl 
    try:
        cfiles = [x for x in os.listdir(CANDROOT) if group in os.path.basename(x)]
    except:
        cfiles = []
    if len(cfiles) > 1:
        # what is this case
        # this shouldn't be the case
        # this should be handled more gracefully TODO
        # for DEBUG purpose
        g_cands = None
        candfile = cfiles[0]
        with open(os.path.join(CANDROOT, candfile), 'r') as f:
            g_cands = cd.CandidateData(f.readlines(), ant = GetAntenna(candfile))
    elif len(cfiles) == 0 :
        # Create a NullCandidateData
        g_cands = cd.NullCandidateData(bm.processor_name)
    else:
        # perfect world case
        candfile = cfiles[0]
        with open(os.path.join(CANDROOT, candfile), 'r') as f:
            g_cands = cd.CandidateData(f.readlines(), ant = GetAntenna(candfile))
    ### gather in ROOT
    group_cands = bm.gather(bm.world, g_cands, ROOT)
    if bm.world.rank == ROOT:
        print group_cands
        print map(lambda x : x.ant, group_cands)
    ## Prometheus exporter
    if enable_prom:
        pass
