#!/usr/bin/python

import argparse

PlotTypes = ['corner', 'fullsky', 'DMtime']
phelp = """
    corner      Corner plot between DM, S/N
    fullsky     Full sky plot of candidates
    DMtime      Candidate DM vs Time with S/N as radius
"""

def parseArgs():
    # for parsing args
    # parent
    pap = argparse.ArgumentParser(prog='cands', description='Command line to tool to visualize, vet candidates.', epilog='Part of Asgard', add_help=False)
    add = pap.add_argument
    add('cand-dir', help='Candidate directories', nargs='*')
    add('-f,fil-dir', help='Fil directories', dest='fdirs')
    add('-g,group', help='Choose groups', dest='groups', nargs='*')
    add('-o,ofile', help='Plot output file', dest='ofile')
    # child
    cap = argparse.ArgumentParser(add_help=False)
    ap = cap.add_subparsers()
    pp = ap.add_parser('plot', description='Plotting options', help='Plotting help', formatter_class=argparse.RawTextHelpFormatter, parents=[pap])
    add = pp.add_argument
    add('-G', action='store_true', help='Do per group')
    add('plottype', help=phelp,  default=None, choices=PlotTypes, metavar='plot-type')



    #
    return cap.parse_args()

if __name__ == '__main__':
    args = parseArgs()
    print args


