#!/usr/bin/python
import numpy as np
import matplotlib.pyplot as plt
import sys

gulpsize = float(sys.argv[1])

l = []
for f in sys.stdin.readlines():
    try:
        ff = float ( f.strip() )
        l.append( ff )
    except:
        print f
fl = np.array(l, dtype=np.float)
lab = "{0:3.2f}\t{1:3.2f}\t{2:3.2f}".format(gulpsize, fl.mean(), fl.max())
print lab
# lab = "gulpsize={0}s mean={1:3.2f} max={2:3.2f}".format(gulpsize, fl.mean(), fl.max())
# plt.hist(fl, bins='auto')
# plt.xlabel('Time (s)')
# plt.yscale('log')
# plt.title(lab)
# plt.savefig('xrfi_{0:03.2f}.pdf'.format(gulpsize), dpi=300)
