#!/bin/bash
# set -x
set -B

if [ $# -eq 0 ]
then
		echo "Asgard::png2pdf"
		echo "Packages grouped pngs to pdf"
		echo "Usage: agpng2pdf <group>"
		exit 0
fi

GROUP=$1
NUM=$(ls | egrep "^${GROUP}" | wc -l)
echo "Found $NUM of $GROUP"
OUT=${GROUP/%png/pdf}

if [ ${NUM} -ge 3 ]; then
		ARG=${GROUP}_{2..${NUM}}
		eval convert ${GROUP} ${ARG} ${OUT}
elif [ ${NUM} -eq 2 ]; then
		ARG=${GROUP}_2
		eval convert ${GROUP} ${1} ${ARG} ${OUT}
elif [ ${NUM} -eq 1 ]; then
		eval convert ${GROUP} $1 ${OUT}
fi

